<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>FourPillars</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Title>FourPillars</Title>
    <Version>0.0.0-alpha</Version>
    <PackageVersion>0.0.0</PackageVersion>
    <AssemblyVersion>0.0.0</AssemblyVersion>
    <FileVersion>0.0.0</FileVersion>
    <Authors>Mao</Authors>
    <Company>Mao</Company>
    <Product>FourPillars</Product>
    <Description>A Modern C# Library for Four Pillars of Destiny (Bazi) Calculation</Description>
    <Copyright>Copyright (c) 2025 Mao</Copyright>
    <PackageTags>astrology, bazi, four-pillars, chinese-metaphysics, yijing, csharp</PackageTags>
    <RepositoryUrl>https://github.com/Akira3Chou/FourPillars.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>logo.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Utilities\" />
  </ItemGroup>

</Project>
